# Generated by Django 5.1.1 on 2024-11-26 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Address')),
                ('status', models.CharField(max_length=20, verbose_name='Check Status')),
                ('check_type', models.CharField(choices=[('SMTP', 'SMTP'), ('IMAP', 'IMAP')], max_length=10, verbose_name='Check Type')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
            ],
            options={
                'verbose_name': 'Email Check',
                'verbose_name_plural': 'Email Checks',
                'ordering': ['-timestamp'],
            },
        ),
    ]
