# Generated by Django 5.1.1 on 2024-11-26 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pooler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=100, verbose_name='Chat ID')),
                ('sender_id', models.CharField(max_length=100, verbose_name='Sender ID')),
                ('date', models.DateTimeField(verbose_name='Message Date')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Message Text')),
                ('message_id', models.CharField(max_length=100, unique=True, verbose_name='Message ID')),
            ],
            options={
                'verbose_name': 'Telegram Message',
                'verbose_name_plural': 'Telegram Messages',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='TelegramFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255, verbose_name='File Name')),
                ('file_path', models.CharField(max_length=500, verbose_name='File Path')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded At')),
                ('telegram_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='pooler.telegrammessage', verbose_name='Related Telegram Message')),
            ],
            options={
                'verbose_name': 'Telegram File',
                'verbose_name_plural': 'Telegram Files',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
