# Generated by Django 5.1.1 on 2024-12-11 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pooler', '0003_uploadedfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailCheck',
        ),
        migrations.RemoveField(
            model_name='telegramfile',
            name='telegram_message',
        ),
        migrations.DeleteModel(
            name='UploadedFile',
        ),
        migrations.DeleteModel(
            name='TelegramFile',
        ),
        migrations.DeleteModel(
            name='TelegramMessage',
        ),
    ]
