services:
  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always
    networks:
      - backend
    command: -c 'max_connections=5000'

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pooler_web
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    volumes:
      - ./uploads:/app/uploads
    networks:
      - backend
    restart: always

  redis:
    image: redis:alpine
    container_name: pooler_redis
    ports:
      - "6379:6379"
    command: redis-server --save "" --appendonly no
    restart: always
    networks:
      - backend
  celery:
    build:
      context: .
    container_name: pooler_celery
    command: celery -A root worker --loglevel=info --concurrency=4
    volumes:
      - .:/app
      - ./data/temp_logs:/app/data/temp_logs
      - ./data/full_logs:/app/data/full_logs
    env_file:
      - .env
    depends_on:
      - db
      - redis
    networks:
      - backend
    restart: always

volumes:
  postgres_data:
  grafana_data:
  prometheus_data:

networks:
  backend:
    driver: bridge
    name: "pooler-net"
