services:
  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB={POSTGRES_DB}
      - POSTGRES_USER={POSTGRES_USER}
      - POSTGRES_PASSWORD={POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pooler_web
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    volumes:
      - ./uploads:/app/uploads
    restart: always

  redis:
    image: redis:alpine
    container_name: pooler_redis
    ports:
      - "6379:6379"
    command: redis-server --save "" --appendonly no
    restart: always

  celery:
    build:
      context: .
    container_name: pooler_celery
    command: celery -A root worker --loglevel=info --concurrency=4
    volumes:
      - .:/app
      - ./data/temp_logs:/app/data/temp_logs
      - ./data/full_logs:/app/data/full_logs
    env_file:
      - .env
    depends_on:
      - db
      - redis
    restart: always

volumes:
  postgres_data:
