version: '3.8'

services:
  db:
    image: postgres:13
    container_name: pooler_db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pooler_web
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
      - static:/app/static
    depends_on:
      db:
        condition: service_healthy
    command: >
      bash -c "python manage.py collectstatic --noinput &&
               python manage.py migrate &&
               python manage.py runserver 0.0.0.0:8000"

volumes:
  postgres_data:
  static: