services:
  db:
    image: postgres:13
    container_name: pooler_db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pooler_web
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./uploads:/app/uploads

  redis:
    image: redis:alpine
    container_name: pooler_redis
    ports:
      - "6379:6379"

  celery:
    build:
      context: .
    container_name: pooler_celery
    command: celery -A root worker --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
      - redis

volumes:
  postgres_data: