# Generated by Django 5.1.1 on 2024-12-11 07:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('file_path', models.TextField()),
                ('upload_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('duplicate_count', models.PositiveIntegerField(default=0)),
                ('origin', models.CharField(choices=[('SMTP', 'SMTP Server'), ('IMAP', 'IMAP Server'), ('MANUAL', 'Manual Upload'), ('TELEGRAM', 'Telegram'), ('UNKNOWN', 'Unknown')], default='MANUAL', max_length=50)),
                ('is_checked', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Uploaded File',
                'verbose_name_plural': 'Uploaded Files',
                'ordering': ['-upload_date'],
            },
        ),
        migrations.CreateModel(
            name='ExtractedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('provider', models.CharField(max_length=100)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('filename', models.CharField(blank=True, max_length=255, null=True)),
                ('smtp_is_valid', models.BooleanField(blank=True, default=None, null=True)),
                ('imap_is_valid', models.BooleanField(blank=True, default=None, null=True)),
                ('uploaded_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extracted_data', to='files.uploadedfile')),
            ],
            options={
                'verbose_name': 'Extracted Data',
                'verbose_name_plural': 'Extracted Data',
            },
        ),
    ]
