# Generated by Django 5.0.8 on 2025-01-26 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=20)),
                ('port', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('country_code', models.CharField(blank=True, max_length=5, null=True)),
                ('anonymity', models.CharField(blank=True, max_length=15, null=True)),
                ('timeout', models.PositiveIntegerField(blank=True, null=True)),
                ('last_time_checked', models.DateTimeField(blank=True, null=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
