"""empty message

Revision ID: 6b99b310bdff
Revises: 3a3bea2eda0f
Create Date: 2024-06-28 13:31:18.065508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b99b310bdff'
down_revision = '3a3bea2eda0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('imap', schema=None) as batch_op:
        batch_op.alter_column('valid',
               existing_type=sa.BOOLEAN(),
               type_=sa.Enum('dead', 'valid', 'spam', 'inbox', 'unknown', name='validstatus'),
               existing_nullable=True)

    with op.batch_alter_table('smtp', schema=None) as batch_op:
        batch_op.alter_column('valid',
               existing_type=sa.BOOLEAN(),
               type_=sa.Enum('dead', 'valid', 'spam', 'inbox', 'unknown', name='validstatus'),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('smtp', schema=None) as batch_op:
        batch_op.alter_column('valid',
               existing_type=sa.Enum('dead', 'valid', 'spam', 'inbox', 'unknown', name='validstatus'),
               type_=sa.BOOLEAN(),
               existing_nullable=True)

    with op.batch_alter_table('imap', schema=None) as batch_op:
        batch_op.alter_column('valid',
               existing_type=sa.Enum('dead', 'valid', 'spam', 'inbox', 'unknown', name='validstatus'),
               type_=sa.BOOLEAN(),
               existing_nullable=True)

    # ### end Alembic commands ###
