# Generated by Django 5.0.8 on 2025-01-26 23:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('provider', models.CharField(max_length=100)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('filename', models.CharField(blank=True, max_length=255, null=True)),
                ('line_number', models.PositiveIntegerField(blank=True, null=True)),
                ('upload_origin', models.CharField(choices=[('SMTP', 'SMTP Server'), ('IMAP', 'IMAP Server'), ('MANUAL', 'Manual Upload'), ('TELEGRAM', 'Telegram'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=50)),
                ('smtp_is_valid', models.BooleanField(blank=True, default=None, null=True)),
                ('imap_is_valid', models.BooleanField(blank=True, default=None, null=True)),
            ],
            options={
                'verbose_name': 'Extracted Data',
                'verbose_name_plural': 'Extracted Data',
            },
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('file_path', models.TextField()),
                ('upload_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('duplicate_count', models.PositiveIntegerField(default=0)),
                ('origin', models.CharField(choices=[('SMTP', 'SMTP Server'), ('IMAP', 'IMAP Server'), ('MANUAL', 'Manual Upload'), ('TELEGRAM', 'Telegram'), ('UNKNOWN', 'Unknown')], default='MANUAL', max_length=50)),
                ('is_checked', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Uploaded File',
                'verbose_name_plural': 'Uploaded Files',
                'ordering': ['-upload_date'],
            },
        ),
        migrations.CreateModel(
            name='URLFetcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=255)),
                ('total_files_fetched', models.PositiveIntegerField(default=0)),
                ('total_lines_added', models.PositiveIntegerField(default=0)),
                ('total_size_fetched', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('last_time_fetched', models.DateTimeField(blank=True, null=True)),
                ('success', models.BooleanField(default=False)),
            ],
        ),
    ]
