# Generated by Django 5.0.8 on 2025-01-28 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_uploadedfile_file_size_uploadedfile_file_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='processing_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='processing_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
