# Generated by Django 5.0.8 on 2025-01-27 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UFWRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('in', 'Inbound'), ('out', 'Outbound')], default='in', max_length=5)),
                ('protocol', models.CharField(choices=[('tcp', 'TCP'), ('udp', 'UDP'), ('any', 'Any')], default='tcp', max_length=5)),
                ('port', models.IntegerField(blank=True, null=True)),
                ('from_ip', models.CharField(blank=True, max_length=35, null=True)),
                ('to_ip', models.CharField(blank=True, max_length=35, null=True)),
                ('action', models.CharField(default='allow', max_length=35)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
